# Generated by Django 3.2.5 on 2021-08-22 21:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210818_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompanyText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text')),
            ],
        ),
    ]
