# Generated by Django 3.2.5 on 2021-08-22 21:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutcompanytext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompanytext',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='aboutcompanytext',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutcompanytext',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=3, verbose_name='Text'),
            preserve_default=False,
        ),
    ]
